[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_proxy = "H8xZNU5ZNAySjGH2yfVWA6V5McxjZZkXN9j6CvC3evko"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/dmitry/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
