[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.31"

[features]
seeds = false
skip-lint = false

[programs.localnet]
oft = "2JTTGs4P4o1i6hKWjD7MCPjnNfUKypFudYdjumHTiL1s"
oft-mock = "BSvVL3d4nAMYkjVHdVA1ryttV25SvVydy1MPAr3dcsdt"
solana_proxy = "Dut1zwap9h9P2FAohfivPyRbuq27TNgsQZuic4RpKzBF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/dmitry/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"
