[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.31"

[features]
seeds = false
skip-lint = false

[programs.localnet]
oft-mock = "BSvVL3d4nAMYkjVHdVA1ryttV25SvVydy1MPAr3dcsdt"
solana_proxy = "H8xZNU5ZNAySjGH2yfVWA6V5McxjZZkXN9j6CvC3evko"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/dmitry/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
